### ISSUE TITLE
How to check whether jmx is enabled through logikm

### ISSUE THREAD

**Issue by moluzhui** [didi/KnowStreaming#504]
After connecting to the kafka cluster, can logik check `whether jmx is enabled`? After connecting to several clusters, it seems that it can be determined by the `broker information` of the `cluster details`. The `unopened` jmx port is **-1**, and the open is another port, but in the document is not explicitly given in.

![image](https://user-images.githubusercontent.com/44611938/178440472-5fb6a90e-717d-494b-a325-8ef2fdb7fd2e.png)

Is it possible to judge based on this -1? Or maybe other observability metrics

Looking forward to your reply.

**Comment by ZQKC** [comment]
> After connecting to the kafka cluster, can logik check `whether jmx is enabled`? After connecting to several clusters, it seems that it can be determined by the `broker information` of the `cluster details`. The `unopened` jmx port is **-1**, and the open is another port, but in the document is not explicitly given in.
> 
> ![image](https://user-images.githubusercontent.com/44611938/178440472-5fb6a90e-717d-494b-a325-8ef2fdb7fd2e.png)
> 
> Is it possible to judge based on this -1? Or maybe other observability metrics
> 
> Looking forward to your reply.

Yes,  the unopened JMX port is -1. But even if the JMX port isn't -1, it may also cause to connect JMX failed due to network impassability and etc. And if the JMX disabled through LogiKM, the LogiKM will print the error log and usually you can solve it by: https://github.com/didi/LogiKM/blob/master/docs/dev_guide/connect_jmx_failed.md

**Comment by ZQKC** [comment]
No more feedback, and close the issue
